apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spamooor
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: spamooor-cronjobs
  source:
    repoURL: https://github.com/astriaorg/spamooor.git
    targetRevision: helm-chart
    path: charts/spamooor-cronjobs
    helm:
      valueFiles:
      - values.yaml