# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Note that these private keys will never contain any real money. They are used for testing purposes only.
jobs:
  erctxsjob:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: ghcr.io/astriaorg/spamooor
      tag: latest
      imagePullPolicy: Always
    schedule: "*/25 * * * *"
    command: ["/app/spamooor"]
    args:
      - "--privkey"
      - "f5419c13c5f5ee39edfebc98a5c595face29efdc50b30b2aae377c220e58d629"
      - "--rpchost"
      - "https://rpc.evm.dusk-7.devnet.astria.org"  # Alternatively: <service-name>.<namespace>.svc.cluster.local:<service-port>
      - "erctx"
      - "--max-wallets"
      - "10"
      - "--throughput"
      - "1000"
      - "--max-pending"
      - "1000"
      - "--count"
      - "15000"
      - "--basefee"
      - "150"
      - "--tipfee"
      - "10"
      - "--timeout"
      - "120"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: Never
  eoatxsjob:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: ghcr.io/astriaorg/spamooor
      tag: latest
      imagePullPolicy: Always
    schedule: "*/15 * * * *"
    command: ["/app/spamooor"]
    args:
      - "--privkey"
      - "a44bc2bb3930e826a602011e0e12e783d6e48d8163042db654039cbbffdd4411"
      - "--rpchost"
      - "https://rpc.evm.dusk-7.devnet.astria.org"  # Alternatively: <service-name>.<namespace>.svc.cluster.local:<service-port>
      - "eoatx"
      - "--max-wallets"
      - "10"
      - "--throughput"
      - "1000"
      - "--max-pending"
      - "1000"
      - "--basefee"
      - "150"
      - "--tipfee"
      - "10"
      - "--count"
      - "15000"
      - "--timeout"
      - "120"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: Never
  gasburnertxsjob:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: ghcr.io/astriaorg/spamooor
      tag: latest
      imagePullPolicy: Always
    schedule: "*/35 * * * *"
    command: ["/app/spamooor"]
    args:
      - "--privkey"
      - "d4d14cafa5c9ab89b8b41479e7c7f9f14999949a40cbcc13e6df9b3782251030"
      - "--rpchost"
      - "https://rpc.evm.dusk-7.devnet.astria.org"  # Alternatively: <service-name>.<namespace>.svc.cluster.local:<service-port>
      - "gasburnertx"
      - "--max-wallets"
      - "10"
      - "--throughput"
      - "5"
      - "--max-pending"
      - "5"
      - "--basefee"
      - "150"
      - "--tipfee"
      - "10"
      - "--count"
      - "50"
      - "--gas-units-to-burn"
      - "5000000"
      - "--timeout"
      - "120"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: Never
  univ2txsjob:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: ghcr.io/astriaorg/spamooor
      tag: latest
      imagePullPolicy: Always
    schedule: "*/45 * * * *"
    command: ["/app/spamooor"]
    args:
      - "--privkey"
      - "64b947d57a7e2633b109875ca71acf13fe8c11237b55616ef87d4a1b907133c8"
      - "--rpchost"
      - "https://rpc.evm.dusk-7.devnet.astria.org"  # Alternatively: <service-name>.<namespace>.svc.cluster.local:<service-port>
      - "univ2tx"
      - "--max-wallets"
      - "10"
      - "--throughput"
      - "1000"
      - "--max-pending"
      - "1000"
      - "--basefee"
      - "150"
      - "--tipfee"
      - "10"
      - "--count"
      - "15000"
      - "--timeout"
      - "120"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
