# Source: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spamooor-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      # PR template vars for this generator:
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Pull-Request/  
      # https://github.com/argoproj/argo-cd/blob/33f5714c832eebee420dad6e14a638915b9ba872/applicationset/generators/pull_request.go#L104
      # {{ .number }}
      # {{ .branch }}
      # {{ .branch_slug }}
      # {{ .target_branch_slug }}
      # {{ .head_sha }}
      # {{ .head_short_sha }}
      # {{ .head_short_sha_7 }}
      # {{ .labels }}
      github:
        owner: astriaorg
        repo: spamooor  # Repository to check for PRs
        tokenRef:
          key: token
          secretName: github-pat
        labels:
          # All of the following labels are required to be set on the PR for the app to be created
        - preview 
      requeueAfterSeconds: 60
  template:
    metadata:
      name: spamooor-{{.number}}
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: spamooor-{{.number}}
      project: default
      source:
        repoURL: https://github.com/astriaorg/spamooor.git
        targetRevision: 'pull/{{.number}}/head' # '{{.head_sha}}'
        path: charts/spamooor-cronjobs
        helm: 
          # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-value-precedence
          # Order of precedence is as follows: 
          #       lowest  -> valueFiles
          #               -> values
          #               -> valuesObject
          #       highest -> parameters
          valueFiles:
          - values.yaml
          parameters:  # Paramters to override default values in values.yaml
          - name: jobs.erctxsjob.image.tag
            value: pr-{{.number}}
          - name: jobs.eoatxsjob.image.tag
            value: pr-{{.number}}
          - name: jobs.univ2txsjob.image.tag
            value: pr-{{.number}}
          - name: jobs.gasburnertxsjob.image.tag
            value: pr-{{.number}}
      syncPolicy:
        automated: {}
        retry:  # Retry/wait because sync will probably fail until the docker image is built and pushed
          limit: 5
          backoff:
            duration: 15s
            factor: 2  # a factor to multiply the base duration after each failed retry
            maxDuration: 5m  # the maximum amount of time allowed for the backoff strategy (15s, 30s, 1m, 2m, 4m < 5m)
        syncOptions:
        - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            # argocd.argoproj.io/instance: <$ARGOCD_APP_NAME>
            argocd.argoproj.io/instance: spamooor-{{.number}}
          annotations:
            # argocd.argoproj.io/tracking-id: <$ARGOCD_APP_NAME>:/Namespace:$ARGOCD_APP_NAMESPACE
            argocd.argoproj.io/tracking-id: spamooor-{{.number}}/Namespace:spamooor-{{.number}}
