# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  curl:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 2000
    image:
      repository: curlimages/curl
      tag: 8.8.0
      imagePullPolicy: Always
    env:
    - name: URL_VAR
      value: "https://curl.se"
    schedule: "0 * * * *"
    args:
      - "-L"
      - "-v"
      - "URL_VAR"
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
